---
name: Documentation Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/docs-lint.yaml'
      - 'docs/**'

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: .go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint

  save-artifacts-on-fail:
    if: ${{ needs.docs-lint.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    if: ${{ needs.depscheck.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
